// let msg = 'hello';
// let msgNew = 'owu';
// let x = 'com';
// let y = 'ua';
// let z = 1;
// let a = 10;
// let b = -999;
// let c = 123;
// let d = 3.14;
// let w = 2.7;
// let num = 16;
// let boolean = true;
// let isFalse = false;
// console.log(msg, msgNew, x, y, z, a, b, c, d, w, num, boolean, isFalse);
// alert(num);
// alert(msg);
// alert(msgNew);
// alert(x);
// alert(y);
// alert(z);
// alert(a);
// alert(b);
// alert(c);
// alert(d);
// alert(w);
// alert(boolean);
// alert(isFalse);
// document.write(msg);
// document.write(msgNew);
// document.write(x);
// document.write(y);
// document.write(y);
// document.write(a);
// document.write(b);
// document.write(c);
// document.write(d);
// document.write(w);
// document.write(num);
// document.write(boolean);
// document.write(isFalse);
// msg = 'world';
// msgNew = 'cool';
// x = 'google';
// y = 258;
// z = 0;
// a = true;
// b = false;
// c = -1000;
// d = 5.5;
// w = -444;
// num = 555;
// boolean = false;
// isFalse = 'zero';
// console.log(msg, msgNew, x, y, z, a, b, c, d, w, num, boolean, isFalse);
// document.write(msg);
// document.write(msgNew);
// document.write(x);
// document.write(y);
// document.write(y);
// document.write(a);
// document.write(b);
// document.write(c);
// document.write(d);
// document.write(w);
// document.write(num);
// document.write(boolean);
// document.write(isFalse);
//
// const firstName = 'Olena';
// const middleName = 'Vasylivna';
// const lastName = 'Lupiy';
// const person = `${firstName} ${middleName} ${lastName}`;
// console.log(person);
// console.log(firstName +' '+middleName + ' ' + lastName);

let firstName = prompt('Enter your first name');
let lastName = prompt('Enter your last name')
let age = prompt('Enter your age');
console.log(`Welcome ${firstName} ${lastName}. You are ${age} years`);

let a = 100;
 let b = '100';
let c = true;
console.log(typeof a);
console.log(typeof b);
console.log(typeof c);

console.log(5<6);
console.log(5>6);
console.log(5===6);
console.log(5>=6);
console.log(10===10);
console.log(10>=10);
console.log(10!=10);
console.log(!!10 === 10);
console.log(10>10);
